/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SIS.Components.Frames;

import SIS.Main;

/**
 *
 * @author user
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderRadioButton = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        idLabel = new javax.swing.JLabel();
        idShowLabel = new javax.swing.JLabel();
        idLabel1 = new javax.swing.JLabel();
        idLabel2 = new javax.swing.JLabel();
        idLabel3 = new javax.swing.JLabel();
        idLabel4 = new javax.swing.JLabel();
        idLabel5 = new javax.swing.JLabel();
        idLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(694, 471));
        setMinimumSize(new java.awt.Dimension(694, 471));
        setPreferredSize(new java.awt.Dimension(694, 471));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 90, 30));

        idLabel.setText("ID NUMBER");
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 30));
        getContentPane().add(idShowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, 30));

        idLabel1.setText("COLLEGE CODE");
        getContentPane().add(idLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, 30));

        idLabel2.setText("FIRST NAME");
        getContentPane().add(idLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, 30));

        idLabel3.setText("LAST NAME");
        getContentPane().add(idLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, 30));

        idLabel4.setText("YEAR LEVEL");
        getContentPane().add(idLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, 30));

        idLabel5.setText("GENDER");
        getContentPane().add(idLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 110, 40));

        idLabel6.setText("PROGRAM CODE");
        getContentPane().add(idLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 120, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 90, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 90, 30));
        getContentPane().add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 130, 30));
        getContentPane().add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, 30));

        genderRadioButton.add(jRadioButton1);
        jRadioButton1.setText("MALE");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        genderRadioButton.add(jRadioButton2);
        jRadioButton2.setText("FEMALE");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 90, 30));

        jButton1.setText("EXIT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Main.disposeAddStudentForm();
    }//GEN-LAST:event_jButton1MouseClicked

    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstNameField;
    private javax.swing.ButtonGroup genderRadioButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JLabel idLabel2;
    private javax.swing.JLabel idLabel3;
    private javax.swing.JLabel idLabel4;
    private javax.swing.JLabel idLabel5;
    private javax.swing.JLabel idLabel6;
    private javax.swing.JLabel idShowLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField lastNameField;
    // End of variables declaration//GEN-END:variables
}
